# -*- coding: utf-8 -*-
"""lab_10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UBrrkIiv_RwYvOBTT6p1N1Uq7dlG0iS6
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/Retail_Dataset_Cleaned (7).csv")
print("Dataset Loaded Successfully")

df.head()
df.info()
df.columns

category_revenue = pd.pivot_table(df,
                                  values="Revenue",
                                  index="Category",
                                  aggfunc= "sum")
category_revenue

city_sales = pd.pivot_table(
    df,
    values="Units_Sold",
    index="City",
    aggfunc="sum"
)
city_sales

df["City"].value_counts().count()

segment_revenue = pd.pivot_table(
    df,
    values="Revenue",
    index="Customer_Segment",
    aggfunc="sum"
)

segment_revenue

category_summary = pd.pivot_table(
    df,
    values="Revenue",
    index="Category",
    aggfunc=["sum","mean","max","min"])
category_summary

channel_summary = pd.pivot_table(
    df,
    values="Units_Sold",
    index="Sales_Channel",
    aggfunc=["sum","mean"]
    )
channel_summary

city_performance= pd.pivot_table(
    df,
    values=["Revenue", "Profit_Margin"],
    index="City",
    aggfunc={
        "Revenue":"sum",
        "Profit_Margin":"mean"
    }
)
city_performance

store_summary = pd.pivot_table(
    df,
    values=["Revenue", "Units_Sold"],
    index="Store_Type",
    aggfunc="sum"
)

store_summary

store_name = pd.pivot_table(
    df,
    values="Profit_Margin",
    index="Store_Name",
    aggfunc="sum"

)
store_name







