# -*- coding: utf-8 -*-
"""lab_8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DQLqmTKQSNJgfsFDZ8yhgldOajrP9WXM
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/Retail_Dataset_Cleaned (4).csv")
print("Dataset Loaded Successfully")

df.head()

df.info()

df.columns

df["Revenue"]

revenue_skew = df["Revenue"].skew()
print(revenue_skew)

if revenue_skew > 0:
  print("Postitiv Skew")
elif revenue_skew < 0:
  print("Negative Skew")
else:
  print("Symmetric Distribution")

skewness =df["Units_Sold"].skew()

if skewness >0:
  print("Postitive skewd distribution")
elif skewness <0:
  print("Negative skewd distribution")
else:
  print("Symmetric distribution")

units_Skew = df["Units_Sold"].skew()
print(units_Skew)

import matplotlib.pyplot as plt

plt.hist(df["Revenue"], bins=20)
plt.title("Revenue Distribution")
plt.xlabel("Revenue")
plt.ylabel("Frequency")
plt.show()

plt.hist(df["Units_Sold"], bins=40)
plt.title("Units Sold Distribution")
plt.xlabel("Units Sold")
plt.ylabel("Frequency")
plt.show()



summary =pd.DataFrame({
    "Metric":["Revenue","Units Sold"],
    "Skewness":[revenue_skew,units_Skew]
})
summary