# -*- coding: utf-8 -*-
"""lab_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pE_VJL-SCPYx239y7u70m74sHHk_L4oS
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/Retail_Dataset_Modified.csv")

print("Dataset Loaded Successfully")

revenue_array = np.array(df["Revenue"])

print(revenue_array)

print("First Revenue Value:")
print(revenue_array[0])

print("Last Revenue Value:")
print(revenue_array[-1])

print("First Five Revenue Values:")
print(revenue_array[0:5])

print("Revenue Values from Index 10 to 20:")
print(revenue_array[10:21])

print("Revenue Values from Index 10 to 20:")
print(revenue_array[10:21])

sales_array = np.array(df[["Units_Sold", "Profit_Margin"]])

print(sales_array)

print("First Row:")
print(sales_array[0])

print("Profit Margin Column:")
print(sales_array[:,1])

first_ten = revenue_array[0:10]
print(first_ten)

print("Total Revenue:")
print(np.sum(first_ten))

print("Maximum Revenue:")
print(np.max(first_ten))

profit_array = np.array(df["Profit_Margin"]) #array_name=np.array (df[column_name]) -> we convert column into array

print(profit_array)







"""#steps
#convert column into array syntax: array_name.array(df['column_name)
#np.method(array_name) -> it will do mathematical calsilation bane on method on array

#work flow
#Read file using pandas -> Convert data into dataframe ->access columns using df[]
>convert columns into array using no.array()-> do calculate on array columns usinf method of numpy

# steps
#1. import liberaries
#2. load data set (reading files)
#2. make data frames
#3.explore data set
#4.data manupulation and data cleaning
#5. visualization
"""