# -*- coding: utf-8 -*-
"""lab_9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i-DKyCEFDAbSYVxUCAHMbf6ewSob_qz3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import binom

df=pd.read_csv("/content/Retail_Dataset_Cleaned (5).csv")

df.head()

df.info()

df.columns

coupons = np.random.randint(1,6,1000)

coupon_counts = pd.Series(coupons).value_counts().sort_index()
print(coupon_counts)

plt.bar(coupon_counts.index, coupon_counts.values)
plt.title("Uniform Distribution of Coupons")
plt.xlabel("Coupon Number")
plt.ylabel("Frequency")
plt.show()

uniform_summary = pd.DataFrame({
    "Coupon": coupon_counts.index,
    "Probability": probabilities.values
})

uniform_summary

probabilities = coupon_counts / coupon_counts.sum()
print(probabilities)

review_count = df["Review_Count"]

review_groups = pd.cut(review_count, bins=10)

review_distribution = review_groups.value_counts().sort_index()
print(review_distribution)

review_distribution.plot(kind='bar')
plt.title("Review Distribution")
plt.xlabel("Review Count")
plt.ylabel("Frequency")
plt.show()

review_probability = review_distribution / review_distribution.sum()
print(review_probability)

uniform_summary = pd.DataFrame({
    "Review Count Range": review_distribution.index.astype(str),
    "Frequency": review_distribution.values,
    "Probability": review_probability.values
})

uniform_summary

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import binom

n=20

p = 0.30

print("Number od Customer:",n)
print("Purchase Probability:", p)

prob_5 = binom.pmf(5,n,p)
print(prob_5)

prob_6 = binom.pmf(6,n,p)
print(prob_6)

prob_10 = binom.pmf(10, n, p)
print(prob_10)

x = np.arange(0, n+1)

y= binom.pmf(x,n,p)

probability_table = pd.DataFrame({
    "Purchases": x,
    "Probability":y})
probability_table.head(10)

plt.figure(figsize=(10,5))
plt.bar(x, y)
plt.title("Binomial Distribution")
plt.xlabel("Number of Purchases")
plt.ylabel("Probability")
plt.show()

most_likely = x[np.argmax(y)]
print("Most Likely Purchases:", most_likely)

expected_purchases = n*p
print(expected_purchases)

summary = pd.DataFrame({
    "Metric": [
        "Number of Customers",
        "Purchase Probability",
        "Expected Purchases",
        "Most Likely Purchases"
    ],
    "Value": [
        n,
        p,
        expected_purchases,
        most_likely
    ]
})

summary